version: "3"
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - "8080:8080"
    build:
      context: ./udagram-reverseproxy
    depends_on:
      - backend-feed
      - backend-user
      - frontend
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"
    build:
      context: ./udagram-frontend
  backend-user:
    image: udagram-api-user
    build:
      context: ./udagram-api-user
    env_file:
      - variables.env
  backend-feed:
    image: udagram-api-feed
    build:
      context: ./udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - variables.env